blocks_to_win:
  type: int
  min: 1
  default: 10
pvp:
  type: boolean
  default: false
keep_inventory:
  type: boolean
  default: true
hunger:
  type: boolean
  default: false
share_blocks:
  type: boolean
  default: true
grace_period_seconds:
  type: int
  min: 0
  default: 0
minutes_per_block:
  type: int
  min: 0
  default: 0