main: beansplusplus.blockshuffle.BlockShufflePlugin
name: BlockShufflePlugin
version: 1
api-version: 1.19
depend:
  - BeansGamePlugin
description: >
  Block shuffle gamemode
commands:
  start:
    description: >
      Begin game
